[package]
name = "test_rust_regex_file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[example]]
name='hello_examples'

[profile.release]
debug = true
